# Generated by Django 5.0.4 on 2024-06-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handyman',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
