# Generated by Django 5.0.4 on 2024-06-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_handyman_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handyman',
            old_name='rating',
            new_name='rating_count',
        ),
        migrations.AddField(
            model_name='handyman',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
